[project]
name = "dpt-ae1"
version = "0.1.0"
description = "Distributed & Parallel Tech - AE1"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3.9.2",
    "pandas>=2.2.3",
]
